---
sidebar: sidebar 
permalink: reference-issues.html 
keywords: issues, bugs, known issues 
summary: Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden. 
---
= Bekannte Probleme
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Probleme identifizieren Probleme, die Sie daran hindern könnten, diese Produktversion erfolgreich zu verwenden.

Bekannte Probleme für die ONTAP-Software finden Sie im https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Versionshinweise zu ONTAP"^].



== Die Anhalten von Nodes kann bei HA-Paaren mit mehreren SVMs fehlschlagen

Wenn Sie einen Cloud Volumes ONTAP Node in einem HA-Paar mit mehreren Storage VMs (SVMs) anhalten oder neu booten möchten, empfehlen wir, alle logischen Schnittstellen (LIFs) vor dem Herunterfahren des Node vorab zu migrieren.

Im folgenden Beispiel werden alle Daten-LIFs vom aktuellen (lokalen) Node migriert:

`node1::> network interface migrate-all -node local`

Diese Aktion erleichtert die Netzwerkübergang zum Partner-Node und vermeidet gelegentlich bekannte Probleme beim Anhalten des Node.

Wenn der Node nicht angehalten werden kann, da die Migration der LIFs zu viel Zeit in Anspruch nimmt, sollte ein erneuter Versuch des Befehls oder der Stopp-Befehl erfolgen.
