---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.7 enthält mehrere neue Funktionen und Verbesserungen. 
---
= Was ist neu in Cloud Volumes ONTAP 9.7
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.7 enthält mehrere neue Funktionen und Verbesserungen.

Zusätzliche Funktionen und Verbesserungen sind auch in den neuesten Versionen von Cloud Manager eingeführt. Siehe https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Versionshinweise Zu Cloud Manager"^] Entsprechende Details.



== 9.7 P6 (15. August 2020)

Der P6-Patch 9.7 für Cloud Volumes ONTAP ist nun über Cloud Manager 3.8 und höher verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P6["Zeigen Sie die Liste der im P6-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== Mehrere Byol-Lizenzen für zusätzliche Kapazität (3. August 2020)

Sie können nun mehrere Lizenzen für ein Cloud Volumes ONTAP BYOL-System erwerben und so mehr als 368 tib Kapazität zuweisen. Beispielsweise können Sie zwei Lizenzen erwerben, um Cloud Volumes ONTAP bis zu 736 tib Kapazität zuzuweisen. Alternativ können Sie vier Lizenzen erwerben, um bis zu 1.4 PiB zu erhalten.

Die Anzahl der Lizenzen, die Sie für ein Single Node-System oder ein HA-Paar erwerben können, ist unbegrenzt.

Beachten Sie, dass die Festplattenbeschränkungen verhindern können, dass Sie durch die Verwendung von Festplatten allein das Kapazitätslimit nicht erreichen. Sie können die Festplattengrenze um überschreiten https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["tiering inaktiver Daten in Objektspeicher"^]. Weitere Informationen zu Festplattenlimits finden Sie in den Storage-Limits in diesen Versionshinweisen.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["Erfahren Sie, wie Sie Cloud Volumes ONTAP zusätzliche Systemlizenzen hinzufügen"^].



== 9.7 P5 in AWS (27 Juli 2020)

Cloud Volumes ONTAP 9.7 P5 ist jetzt in AWS verfügbar. Diese Patch-Version beinhaltet Bug Fixes und Unterstützung für neue EC2 Instanztypen.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["Zeigen Sie die Liste der im P5-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



=== Unterstützung für neue EC2 Instanztypen

Cloud Volumes ONTAP unterstützt jetzt die folgenden EC2-Instanztypen mit den Lizenzen Premium und BYOL:

* C5n.9xlarge
* C5n.18xlarge




== 9.7 P5 in Azure (20. Juli 2020)

Cloud Volumes ONTAP 9.7 P5 ist jetzt in Microsoft Azure verfügbar. Diese Patch-Version beinhaltet Bug Fixes und Unterstützung für neue VM-Typen.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["Zeigen Sie die Liste der im P5-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



=== Unterstützung neuer VM-Typen mit Ultra SSD VNVRAM

Cloud Volumes ONTAP unterstützt jetzt die folgenden VM-Typen mit Single-Node-Systemen, die über eine Premium- oder BYOL-Lizenz verfügen:

* Standard_E32s_v3
* Standard_E48s_v3


Der VM-Typ E32s_v3 verwendet ein https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["Ultra SSD"^] Für VNVRAM-Speicher, das eine bessere Schreib-Performance bietet.

Für diese VM-Typen werden derzeit in den folgenden Regionen unterstützt: US Gov Virginia, South Central US und West US.



== Unterstützung mehrerer Storage VMs in AWS (16. Juli 2020)

Cloud Volumes ONTAP 9.7 unterstützt jetzt mehrere Storage VMs (SVMs) in AWS.

Mehrere Storage VMs werden mit den Instanztypen C5, M5 und R5 unterstützt, wenn Sie Ihre eigene Lizenz (BYOL) mitbringen. Folgende Anzahl von Storage-VMs wird unterstützt:

* 12 Storage VMs mit Single Node Systemen
* 8 Storage VMs mit HA-Paaren


Für jede zusätzliche „ _datenServing_ Storage VM“ über die erste Storage VM hinaus, die standardmäßig mit Cloud Volumes ONTAP konfiguriert ist, ist eine Add-on-Lizenz erforderlich. Wenden Sie sich an Ihr Account-Team, um eine SVM-Add-on-Lizenz zu erhalten.

Storage VMs, die Sie für die Disaster Recovery (DR) konfigurieren, erfordern keine zusätzliche Lizenz (sie sind kostenlos), werden aber an die Storage-VM-Grenze angerechnet.

Wenn Sie beispielsweise 8 Daten-Serving-VMs auf einem HA-Paar haben, dann haben Sie das Limit erreicht und Sie können keine zusätzlichen Storage VMs erstellen. Das gleiche gilt für ein anderes HA-Paar, das 8 Storage VMs für Disaster Recovery konfiguriert hat. Sie haben das Limit erreicht und können keine zusätzlichen Storage VMs erstellen.

Das Erstellen zusätzlicher Storage VMs muss über System Manager oder die CLI erfolgen.



== Deutschland Sovereign Regions in Azure werden nicht mehr unterstützt (26. Juni 2020)

Cloud Volumes ONTAP wird in den folgenden Azure Regionen nicht mehr unterstützt:

* Deutschland Mitte (Souverän)
* Deutschland, Nordosten (Souverän)


NetApp unterstützt Cloud Volumes ONTAP auch weiterhin in den öffentlichen Regionen Deutschland:

* Deutschland Nord (Öffentlich)
* Deutschland West Central (Öffentlich)


https://cloud.netapp.com/cloud-volumes-global-regions["Eine vollständige Liste der unterstützten Azure Regionen ist verfügbar"^].



== 9.7 P4 (2. Juni 2020)

Der Patch-Release 9.7 P4 für Cloud Volumes ONTAP ist nun über Cloud Manager 3.8 und höher verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P4["Hier finden Sie eine Liste der im P4-Patch fixierten Fehler"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.7 P3 (2 Mai 2020)

Der 9.7 P3-Patch für Cloud Volumes ONTAP ist nun über Cloud Manager 3.8 und höher verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P3["Zeigen Sie die Liste der im P3-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== 9.7 P2 (8. April 2020)

Der 9.7 P2-Patch für Cloud Volumes ONTAP ist jetzt über Cloud Manager 3.8 und höher erhältlich. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P2["Zeigen Sie die Liste der im P2-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== Erhöhte Festplattenkapazität in Google Cloud (13. März 2020)

Sie können nun bis zu 256 tib persistente Festplatten an Cloud Volumes ONTAP anschließen, wenn Sie die Premium- oder BYOL-Lizenzen in Google Cloud verwenden. Dies entspricht einem Speicher von 64 TB.

Wie zuvor können Sie die maximale Systemkapazität für Premium und BYOL von 368 tib erreichen, indem Sie persistente Festplatten mit Daten-Tiering in Objekt-Storage kombinieren.

Die maximale Anzahl der Datendisks pro System hat sich ebenfalls auf 124 Disks erhöht.

* link:reference-configs-gcp.html["Erfahren Sie mehr über die unterstützten Konfigurationen für Cloud Volumes ONTAP in Google Cloud"]
* link:reference-limits-gcp.html["Prüfen Sie Storage-Limits in Google Cloud"]




== 9.7 P1 (6. März 2020)

Der Patch 9.7 P1 für Cloud Volumes ONTAP ist nun über Cloud Manager 3.8 und höher verfügbar. Cloud Manager fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P1["Zeigt die Liste der im P1-Patch fixierten Fehler an"^] (Anmeldung auf der NetApp Support Site erforderlich).



== AWS Updates (16. Feb. 2020)

Unterstützung für neue EC2 Instanzen und eine Änderung der Anzahl unterstützter Datenfestplatten sind eingeführt.



=== Unterstützung für neue Instanzen

In Cloud Volumes ONTAP 9.7 werden nun mehrere neue EC2-Instanztypen unterstützt, wenn eine Premium- oder BYOL-Lizenz verwendet wird:

* C5.9xlarge
* C5d.18xlarge ^1^
* M5d.8xlarge ^1^
* M5d.12xlarge ^1^
* M5.16 x groß
* R5.8 x groß
* R5.12 x groß ^2^


^1^ zu diesen Instanztypen gehört lokaler NVMe-Storage, der Cloud Volumes ONTAP als _Flash Cache_ verwendet. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["Weitere Informationen ."^].

^2^ der Instanztyp r5.12xlarge weist eine bekannte Beschränkung der Support-Möglichkeiten auf. Wenn ein Node aufgrund eines Panikzustands neu gebootet wird, erfasst das System möglicherweise keine Kerndateien, die zur Fehlerbehebung und zum Beheben des Problems verwendet werden. Der Kunde akzeptiert die Risiken und die eingeschränkten Supportbedingungen und trägt in diesem Fall die gesamte Supportverantwortung.

https://aws.amazon.com/ec2/instance-types/["Weitere Informationen zu diesen EC2 Instanztypen"^].

link:reference-configs-aws.html["Hier erhalten Sie weitere Informationen zu unterstützten 9.7 Konfigurationen in AWS"].



=== Unterstützte Datenfestplatten

Eine Datenfestplatte weniger wird nun für c5-, m5- und r5-Instanzen unterstützt. Bei Single Node-Systemen werden 22 Datenfestplatten unterstützt. Bei HA-Paaren werden pro Node 19 Datenfestplatten unterstützt.

link:reference-limits-aws.html["Erfahren Sie mehr über Storage-Limits in AWS"].



== Support für DS15_v2 in Azure (12. Feb 2020)

Cloud Volumes ONTAP wird jetzt mit dem virtuellen Maschinentyp DS15_v2 in Azure unterstützt, sowohl auf Single Node-Systemen als auch auf HA-Paaren.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Weitere Informationen zur DSv2 Serie"^].

link:reference-configs-azure.html["Hier erhalten Sie weitere Informationen zu unterstützten 9.7 Konfigurationen in Azure"].



== 9.7 GA (10. Februar 2020)

Das GA-Release (General Availability) von Cloud Volumes ONTAP 9.7 ist jetzt auch in AWS und Google Cloud verfügbar. Die GA-Version enthält Bug Fixes. Cloud Manager fordert Sie zum Upgrade Ihrer vorhandenen Systeme auf diese Version auf.



== 9.7 D1 für Azure (29. Januar 2020)

Cloud Volumes ONTAP 9.7 D1 ist nun in Microsoft Azure verfügbar.

Wir haben ein Problem mit Cloud Volumes ONTAP 9.7 und früher entdeckt, wo Cloud Volumes ONTAP in Situationen, in denen die virtuelle Azure Maschine neu gestartet wird, nicht erfolgreich gestartet wird.

Dieses Problem wurde in 9.7 D1 (und höher) behoben. Wir empfehlen dringend, so bald wie möglich auf die neueste Cloud Volumes ONTAP-Version zu aktualisieren.

Wenn Sie Fragen haben, kontaktieren Sie uns bitte über den in-Product-Chat oder unter https://www.netapp.com/us/contact-us/support.aspx[].



== 9.7 RC1 (16 Dezember 2019)

Cloud Volumes ONTAP 9.7 RC1 ist jetzt auf der AWS, Azure und Google Cloud Platform verfügbar. Zusätzlich zu den bereits mit eingeführten Funktionen https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.7"^], Diese Version von Cloud Volumes ONTAP enthält die folgenden:

*  Cache support in Azure
*  for Azure NIC detach events




=== Flash Cache-Unterstützung in Azure

Cloud Volumes ONTAP unterstützt jetzt den VM-Typ Standard_L8S_v2 mit einem einzelnen Node sowie BYOL-Systemen in Azure. Dieser VM-Typ umfasst lokalen NVMe-Storage, den Cloud Volumes ONTAP als _Flash Cache_ verwendet.

Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services.

Neue Systeme können mit diesem VM-Typ implementiert oder vorhandene Systeme angepasst werden, um diesen VM-Typ zu verwenden. Außerdem profitieren Sie automatisch von Flash Cache.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["Erfahren Sie mehr über die Aktivierung von Flash Cache auf Cloud Volumes ONTAP, einschließlich einer Einschränkung der Datenkomprimierung"^].



=== Ereignisse zum Trennen der Azure NIC beheben

Dieser Release behebt ein Problem, wenn beim Neubooten von Cloud Volumes ONTAP-Nodes aus dem Trennen der Azure NIC Ereignisse ein Problem auftritt. Cloud Volumes ONTAP übernimmt diese Ereignisse weniger und der Betrieb wird nicht unterbrochen. Cloud Volumes ONTAP HA-Paare führen weiterhin eine Takeover-/Giveback-Sequenz aus Azure Freeze-Wartungsereignissen aus, aber es gibt keinen nachfolgenden Neustart eines NIC-Abfalls, der während dieser Zeit auftreten kann.



== Upgrade-Hinweise

* Upgrades von Cloud Volumes ONTAP müssen von Cloud Manager abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.
* Sie können ein Upgrade von Version 9.6 auf Cloud Volumes ONTAP 9.7 durchführen. Cloud Manager fordert Sie zum Upgrade Ihrer vorhandenen Cloud Volumes ONTAP 9.6 Systeme auf Version 9.7 auf.
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Informieren Sie sich, wie ein Upgrade durchgeführt wird, wenn Cloud Manager Sie benachrichtigt"^].

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars erfolgt unterbrechungsfrei und die I/O wird unterbrochen. Während dieses unterbrechungsfreien Upgrade-Prozesses wird jeder Node entsprechend aktualisiert, um den I/O-Datenverkehr für die Clients weiterhin bereitzustellen.

